import fs from 'node:fs/promises';
const FILE=new URL('../../src/data/events.json',import.meta.url),TODAY=new Date().toISOString().slice(0,10),UA='TassieNow/0.4 (+https://tassienow.pages.dev)';
const SOURCES=[{name:'City of Hobart',url:'https://www.hobartcity.com.au/Things-To-Do/Upcoming-events',town:'Hobart',region:'Hobart & South'},{name:'City of Launceston',url:'https://www.launceston.tas.gov.au/Upcoming-Events',town:'Launceston',region:'Launceston & North'},{name:'Burnie City Council',url:'https://www.burnie.tas.gov.au/Community/Whats-On-Events',town:'Burnie',region:'North West'}];
const M={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};
const slug=v=>String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90);const dec=v=>String(v||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;|&#x27;/gi,"'").replace(/&ndash;|&#8211;/gi,'–').replace(/&mdash;|&#8212;/gi,'—');const clean=v=>dec(String(v||'').replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();
function fallback(name){return{url:'/images/categories/events.svg',alt:`${name} event category image`,attribution:'TassieNow',license:'Site artwork',licenseUrl:null,sourceUrl:null,isFallback:true};}
async function fetchHtml(url){const r=await fetch(url,{headers:{'user-agent':UA,accept:'text/html,*/*;q=.8'},signal:AbortSignal.timeout(45000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.text();}
function flatten(v,o=[]){if(!v)return o;if(Array.isArray(v)){v.forEach(x=>flatten(x,o));return o}if(typeof v!=='object')return o;const t=v['@type'];if((Array.isArray(t)?t:[t]).includes('Event'))o.push(v);for(const x of Object.values(v))if(typeof x==='object')flatten(x,o);return o;}
function jsonld(html){const o=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{flatten(JSON.parse(m[1].trim()),o)}catch{}}return o;}
function date(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.valueOf())?null:d.toISOString().slice(0,10)}function parts(day,mon,year){const n=M[String(mon).toLowerCase()];if(!n)return null;return`${year}-${String(n).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}
function lines(html){return dec(String(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<(?:br\s*\/?|\/p|\/div|\/li|\/article|\/a|\/h[1-6]|\/section)>/gi,'\n').replace(/<[^>]+>/g,' ')).split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);}
function textEvents(html,s){const l=lines(html),out=[],re=/(?:^|\b)(\d{1,2})\s+(Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:t(?:ember)?)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(20\d{2})(?:\b|\s*[-–—:]\s*)(.*)$/i;for(let i=0;i<l.length;i++){const m=l[i].match(re);if(!m)continue;const startDate=parts(m[1],m[2],m[3]);if(!startDate||startDate<TODAY)continue;const horizon=new Date();horizon.setUTCDate(horizon.getUTCDate()+240);if(startDate>horizon.toISOString().slice(0,10))continue;let name=clean(m[4]);if(name.length<3&&l[i+1]&&!re.test(l[i+1]))name=clean(l[i+1]);name=name.replace(/^(event|what'?s on|calendar)\s*[:–—-]?\s*/i,'').trim();if(name.length<3||name.length>160||/^(monday|tuesday|wednesday|thursday|friday|saturday|sunday)$/i.test(name))continue;const context=`${name} ${l[i+1]||''}`,categories=['Events'];if(/\bfree\b/i.test(context))categories.push('Free');if(/family|kids|children|child/i.test(context))categories.push('Family');out.push({slug:slug(`${name}-${startDate}-${s.town}`),name,town:s.town,region:s.region,startDate,endDate:startDate,categories,summary:`${name} in ${s.town}. Check the official ${s.name} listing for current time, venue and booking details.`,eventUrl:s.url,sourceUrl:s.url,sourceName:s.name,image:fallback(name),status:'active',lastChecked:TODAY});}return out;}
const found=[];for(const s of SOURCES){try{const html=await fetchHtml(s.url),structured=jsonld(html);let count=0;for(const e of structured){const startDate=date(e.startDate),endDate=date(e.endDate||e.startDate);if(!startDate||!endDate||endDate<TODAY)continue;const horizon=new Date();horizon.setUTCDate(horizon.getUTCDate()+240);if(startDate>horizon.toISOString().slice(0,10))continue;const name=clean(e.name);if(!name)continue;const town=clean(e.location?.address?.addressLocality||e.location?.name||s.town),description=clean(e.description).slice(0,280),categories=['Events'];if(/\bfree\b/i.test(description))categories.push('Free');if(/family|kids|children/i.test(description))categories.push('Family');found.push({slug:slug(`${name}-${startDate}-${town}`),name,town,region:s.region,startDate,endDate,categories,summary:description||`Event in ${town}. Check the official event source for current details.`,eventUrl:e.url||s.url,sourceUrl:s.url,sourceName:s.name,image:fallback(name),status:'active',lastChecked:TODAY});count++;}if(!count){const f=textEvents(html,s);found.push(...f);count=f.length;console.log(`${s.name}: HTML fallback ${count} event(s).`)}else console.log(`${s.name}: ${count} structured event(s).`)}catch(e){console.warn(`${s.name}: ${e.message}`)}}const seen=new Set(),unique=[];for(const e of found){const k=`${e.name.toLowerCase()}|${e.startDate}|${e.town.toLowerCase()}`;if(!seen.has(k)){seen.add(k);unique.push(e)}}unique.sort((a,b)=>a.startDate.localeCompare(b.startDate)||a.name.localeCompare(b.name));await fs.writeFile(FILE,`${JSON.stringify(unique,null,2)}\n`);console.log(`Events: ${unique.length} active.`);
