import fs from 'node:fs/promises';
import { regionFor } from './lib/regions.mjs';

const FILE = new URL('../../src/data/places.json', import.meta.url);
const USER_AGENT = 'TassieNow/0.8 (+https://tassienow.pages.dev)';
const TARGET = 520;
const FULL = '-43.75,143.55,-39.15,148.65';
const BOXES = [
  ['south-east', '-43.75,146.0,-42.0,148.65'],
  ['north-east', '-42.0,146.0,-39.15,148.65'],
  ['south-west', '-43.75,143.55,-42.0,146.0'],
  ['north-west', '-42.0,143.55,-39.15,146.0']
];
const ENDPOINTS = [
  'https://maps.mail.ru/osm/tools/overpass/api/interpreter',
  'https://overpass.private.coffee/api/interpreter',
  'https://overpass-api.de/api/interpreter'
];
const TYPES = {
  attraction:['Things to Do'], museum:['Museums','Art & Culture','Rainy Day'], gallery:['Art & Culture','Rainy Day'], arts_centre:['Art & Culture','Rainy Day','Things to Do'], historic_site:['History','Things to Do','Outdoor'], restaurant:['Food & Drink'], cafe:['Food & Drink'], fast_food:['Food & Drink'], food_court:['Food & Drink'], pub:['Food & Drink'], bakery:['Food & Drink'], street_vendor:['Food & Drink'], heritage_building:['History','Things to Do'],  zoo:['Wildlife','Family'], aquarium:['Wildlife','Family','Rainy Day'], theme_park:['Family'], viewpoint:['Nature & Walks','Outdoor'], marketplace:['Markets','Food & Drink'], farm:['Local Produce','Food & Drink'], nature_reserve:['Nature & Walks','Outdoor'], playground:['Family','Outdoor'], beach:['Nature & Walks','Outdoor'], winery:['Food & Drink','Local Produce'], brewery:['Food & Drink','Local Produce'], distillery:['Food & Drink','Local Produce'], hiking:['Nature & Walks','Outdoor']
};

function tasDate(date = new Date()) {
  const parts = new Intl.DateTimeFormat('en-AU', { timeZone:'Australia/Hobart', year:'numeric', month:'2-digit', day:'2-digit' }).formatToParts(date);
  const get = (type) => parts.find((part) => part.type === type)?.value;
  return `${get('year')}-${get('month')}-${get('day')}`;
}
const TODAY = tasDate();
const slugify=(v)=>String(v).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90);
const norm=(v='')=>String(v).toLowerCase().replace(/[^a-z0-9]/g,'');
const clean=(v='')=>String(v).replace(/<[^>]*>/g,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim();
const mail=(v='')=>{const x=clean(v);return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)?x:null};
const phone=(v='')=>clean(v).replace(/^tel:/i,'')||null;
function addressFromTags(t={}){const street=[t['addr:housenumber'],t['addr:street']].filter(Boolean).map(clean).join(' '),locality=clean(t['addr:suburb']||t['addr:city']||t['addr:town']||t['addr:place']),state=clean(t['addr:state']||'TAS'),postcode=clean(t['addr:postcode']);const parts=[street,locality,state,postcode].filter(Boolean);return parts.length>=2?parts.join(', '):null}
function wikipediaUrl(v=''){const raw=clean(v);if(!raw)return null;if(/^https?:\/\//i.test(raw))return url(raw);const m=/^([a-z-]{2,12}):(.*)$/.exec(raw);if(!m)return null;return `https://${m[1]}.wikipedia.org/wiki/${encodeURIComponent(m[2].replace(/ /g,'_'))}`}
function osmDetailSources(t={},sourceUrl=''){const map={openingHours:t.opening_hours,phone:t['contact:phone']||t.phone,email:t['contact:email']||t.email,address:addressFromTags(t),bookingUrl:t.booking||t.reservation||t['contact:booking'],fee:t.fee,wheelchair:t.wheelchair,operator:t.operator};const out={};for(const [key,value] of Object.entries(map))if(value!=null&&clean(value)!=='')out[key]={type:'openstreetmap',url:sourceUrl,checkedAt:TODAY};return out}
function url(value){if(!value)return null;const c=/^https?:\/\//i.test(String(value).trim())?String(value).trim():`https://${String(value).trim()}`;try{const u=new URL(c);return ['http:','https:'].includes(u.protocol)?c:null}catch{return null}}
function coords(e){if(Number.isFinite(e.lat)&&Number.isFinite(e.lon))return[e.lat,e.lon];if(Number.isFinite(e.center?.lat)&&Number.isFinite(e.center?.lon))return[e.center.lat,e.center.lon];return[null,null]}
function inTasmania(lat,lon){return Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-44&&lat<=-39&&lon>=143&&lon<=149}
function km(a,b,c,d){const r=x=>x*Math.PI/180,dy=r(c-a),dx=r(d-b),z=Math.sin(dy/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dx/2)**2;return 6371*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z))}
function kind(t={}){if(t.tourism==='attraction'&&['manor','heritage','yes'].includes(t.historic))return'heritage_building';if(t.tourism&&TYPES[t.tourism])return t.tourism;if(t.amenity==='arts_centre')return'arts_centre';if(['archaeological_site','ruins','castle','fort','mine','wreck','battlefield','monument','wayside_shrine'].includes(t.historic))return'historic_site';if(t.amenity==='pub')return /^(?:yes|only|limited|full)$/i.test(t['food:serving']||t.food||'')?'pub':null;if(['restaurant','cafe','fast_food','food_court'].includes(t.amenity))return t.amenity;if(t.shop==='bakery')return'bakery';if(t.amenity==='mobile_food_vendor'||(t.shop==='food'&&t.mobile==='yes'))return'street_vendor';if(t.amenity==='marketplace')return'marketplace';if(t.shop==='farm')return'farm';if(t.leisure==='nature_reserve')return'nature_reserve';if(t.leisure==='playground')return'playground';if(t.natural==='beach')return'beach';if(['winery','brewery','distillery'].includes(t.craft))return t.craft;if(t.route==='hiking')return'hiking';return null}
function categories(t,k){const c=new Set(TYPES[k]||['Things to Do']);const foodKinds={restaurant:'Restaurant',cafe:'Café',fast_food:'Takeaway',food_court:'Takeaway',pub:'Pub Food',bakery:'Bakery',street_vendor:'Food Van'};if(foodKinds[k])c.add(foodKinds[k]);if(k==='street_vendor' || t.mobile==='yes' || t['mobile:food']==='yes')c.add('Mobile Vendor');if(t.fee==='no')c.add('Free');if(t.indoor==='yes')c.add('Rainy Day');if(t.family==='yes'||t.kids==='yes')c.add('Family');return[...c]}
function fallback(c){const v=c.join('|').toLowerCase();let n='discover';if(v.includes('museum')||v.includes('art & culture')||v.includes('history'))n='culture';else if(v.includes('wildlife'))n='wildlife';else if(v.includes('market')||v.includes('food')||v.includes('local produce'))n='food';else if(v.includes('family'))n='family';else if(v.includes('nature')||v.includes('outdoor'))n='nature';return{url:`/images/categories/${n}.svg`,attribution:'TassieNow',license:'Site artwork',licenseUrl:null,sourceUrl:null,isFallback:true}}
function score(t,k){let s=({museum:14,zoo:14,aquarium:14,theme_park:13,gallery:12,arts_centre:11,attraction:11,historic_site:10,heritage_building:11,restaurant:8,cafe:8,fast_food:7,food_court:7,pub:7,bakery:7,street_vendor:6,marketplace:10,winery:10,distillery:10,brewery:9,nature_reserve:9,hiking:9,viewpoint:8,beach:7,farm:7,playground:5}[k]||4);if(t.website||t['contact:website'])s+=4;if(t.wikidata||t.wikimedia_commons||t.wikipedia)s+=5;if(t.opening_hours)s+=2;if(t.operator)s++;if(t.fee)s++;return s}
function summary(k,town,t){const at=town?` in or near ${town}`:' in Tasmania',op=t.operator?` Operated by ${clean(t.operator)}.`:'';const m={museum:`Museum${at}.`,gallery:`Gallery and arts destination${at}.`,arts_centre:`Arts and cultural centre${at}.`,historic_site:`Historic site${at}.`,heritage_building:`Heritage attraction${at}.`,restaurant:`Restaurant${at}.`,cafe:`Café${at}.`,fast_food:`Takeaway food venue${at}.`,food_court:`Food court${at}.`,pub:`Pub${at}; confirm food service before visiting.`,bakery:`Bakery${at}.`,street_vendor:`Food vendor${at}; confirm the current trading location.`, zoo:`Wildlife attraction${at}.`,aquarium:`Aquarium and wildlife attraction${at}.`,theme_park:`Family attraction${at}.`,attraction:`Visitor attraction${at}.`,viewpoint:`Scenic viewpoint${at}.`,marketplace:`Market${at}.`,farm:`Farm-gate or local-produce destination${at}.`,nature_reserve:`Nature reserve${at}.`,playground:`Named playground or family recreation area${at}.`,beach:`Named beach${at}.`,winery:`Winery or cellar-door destination${at}.`,brewery:`Brewery destination${at}.`,distillery:`Distillery destination${at}.`,hiking:`Named walking or hiking route${at}.`};return`${m[k]||`Visitor destination${at}.`}${op}`.trim()}
async function fetchText(u,o={}){const r=await fetch(u,{...o,headers:{'user-agent':USER_AGENT,accept:'*/*',...(o.headers||{})},signal:AbortSignal.timeout(o.timeout||18000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.text()}
const fetchJson=async(u,o={})=>JSON.parse(await fetchText(u,o));
async function overpass(label,body,{maxEndpoints=ENDPOINTS.length,timeout=18000,queryTimeout=12}={}){const q=`[out:json][timeout:${queryTimeout}];(${body});out body center;`;let last;for(const ep of ENDPOINTS.slice(0,maxEndpoints)){try{const d=await fetchJson(ep,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({data:q}).toString(),timeout});if(d.remark&&/runtime error|timed out/i.test(d.remark))throw new Error(d.remark);console.log(`${label}: ${d.elements?.length||0} OSM element(s) via ${new URL(ep).hostname}.`);return d.elements||[]}catch(e){last=e;console.warn(`${label} failed at ${ep}: ${e.message}`)}}console.warn(`${label}: skipped after ${maxEndpoints} endpoint attempt(s): ${last?.message||'unknown error'}`);return[]}
async function discover(){
  const all=[];
  for(const [label,box] of BOXES){
    all.push(...await overpass(`core-${label}`,`node["place"~"^(city|town|village)$"]["name"](${box});nwr["tourism"~"^(attraction|museum|gallery|zoo|aquarium|theme_park|viewpoint)$"]["name"](${box});`,{maxEndpoints:3,timeout:18000,queryTimeout:12}));
  }
  all.push(...await overpass('markets-produce',`nwr["amenity"="marketplace"]["name"](${FULL});nwr["shop"="farm"]["name"](${FULL});nwr["craft"~"^(winery|brewery|distillery)$"]["name"](${FULL});`,{maxEndpoints:1,timeout:12000,queryTimeout:8}));
  all.push(...await overpass('culture-history',`nwr["amenity"="arts_centre"]["name"](${FULL});nwr["historic"~"^(archaeological_site|ruins|castle|fort|mine|wreck|battlefield|monument|wayside_shrine)$"]["name"](${FULL});`,{maxEndpoints:2,timeout:15000,queryTimeout:10}));
  all.push(...await overpass('food-stops',`nwr["amenity"~"^(restaurant|cafe|fast_food|food_court|pub|mobile_food_vendor)$"]["name"](${FULL});nwr["shop"~"^(bakery|food)$"]["name"](${FULL});`,{maxEndpoints:2,timeout:18000,queryTimeout:12}));
  all.push(...await overpass('walks-nature',`rel["route"="hiking"]["name"](${FULL});nwr["natural"="beach"]["name"](${FULL});nwr["leisure"="nature_reserve"]["name"](${FULL});`,{maxEndpoints:1,timeout:12000,queryTimeout:8}));
  all.push(...await overpass('family-playgrounds',`nwr["leisure"="playground"]["name"](${FULL});`,{maxEndpoints:1,timeout:12000,queryTimeout:8}));
  const unique=new Map();for(const e of all)unique.set(`${e.type}/${e.id}`,e);return[...unique.values()]
}
function nearest(lat,lon,list){let best=null,d=Infinity;for(const p of list){const x=km(lat,lon,p.latitude,p.longitude);if(x<d){best=p;d=x}}return d<=70?best?.name||'':''}
async function wikidata(ids){const out=new Map(),u=[...new Set(ids.filter(Boolean))];for(let i=0;i<u.length;i+=50){const b=u.slice(i,i+50),x=new URL('https://www.wikidata.org/w/api.php');x.searchParams.set('action','wbgetentities');x.searchParams.set('format','json');x.searchParams.set('props','claims');x.searchParams.set('ids',b.join('|'));try{const d=await fetchJson(x,{timeout:15000});for(const id of b){const f=d.entities?.[id]?.claims?.P18?.[0]?.mainsnak?.datavalue?.value;if(f)out.set(id,f)}}catch(e){console.warn(`Wikidata image batch skipped: ${e.message}`)}}return out}
async function commons(titles){const out=new Map(),u=[...new Set(titles.filter(Boolean).map(t=>t.replace(/^File:/i,'')))];for(let i=0;i<u.length;i+=30){const b=u.slice(i,i+30),x=new URL('https://commons.wikimedia.org/w/api.php');x.searchParams.set('action','query');x.searchParams.set('format','json');x.searchParams.set('prop','imageinfo');x.searchParams.set('iiprop','url|extmetadata');x.searchParams.set('iiurlwidth','1200');x.searchParams.set('titles',b.map(v=>`File:${v}`).join('|'));try{const d=await fetchJson(x,{timeout:15000});for(const p of Object.values(d.query?.pages||{})){const info=p.imageinfo?.[0];if(!info)continue;const f=p.title.replace(/^File:/i,''),m=info.extmetadata||{};out.set(f,{url:info.thumburl||info.url,sourceUrl:info.descriptionurl||null,attribution:clean(m.Artist?.value||m.Credit?.value||'')||'Wikimedia Commons contributor',license:clean(m.LicenseShortName?.value||m.UsageTerms?.value||'Wikimedia Commons'),licenseUrl:m.LicenseUrl?.value||null,isFallback:false})}}catch(e){console.warn(`Commons image batch skipped: ${e.message}`)}}return out}
function balanced(records,limit){const buckets=new Map();for(const r of records.sort((a,b)=>b._score-a._score||a.name.localeCompare(b.name))){if(!buckets.has(r.region))buckets.set(r.region,[]);buckets.get(r.region).push(r)}const out=[],rs=[...buckets.keys()].sort();let i=0;while(out.length<limit&&rs.some(r=>buckets.get(r).length)){const b=buckets.get(rs[i%rs.length]);if(b.length)out.push(b.shift());i++}return out}

const elements=await discover();
console.log(`Unique OSM response elements: ${elements.length}.`);
const localities=elements.filter(e=>e.tags?.place&&['city','town','village'].includes(e.tags.place)&&e.tags.name).map(e=>{const[latitude,longitude]=coords(e);return{name:e.tags.name,latitude,longitude}}).filter(p=>inTasmania(p.latitude,p.longitude));
const candidates=[];const counts={};
for(const e of elements){const t=e.tags||{},k=kind(t);if(!k||!t.name||['private','no'].includes(t.access)||t.disused==='yes'||t.abandoned==='yes'||t.demolished==='yes'||t['disused:amenity']||t['disused:shop']||t['abandoned:amenity']||t['abandoned:shop'])continue;const[latitude,longitude]=coords(e);if(!inTasmania(latitude,longitude))continue;const town=clean(t['addr:city']||t['addr:town']||t['addr:suburb']||t['addr:place']||nearest(latitude,longitude,localities)||'Tasmania'),c=categories(t,k);{const sourceUrl=`https://www.openstreetmap.org/${e.type}/${e.id}`;candidates.push({slug:slugify(t.name),name:clean(t.name),town,region:regionFor(latitude,longitude,town),latitude,longitude,categories:c,summary:summary(k,town,t),website:url(t.website||t['contact:website']),sourceUrl,sourceType:'openstreetmap',sourceId:`${e.type}/${e.id}`,wikidata:t.wikidata||null,wikipediaUrl:wikipediaUrl(t.wikipedia),commonsCategory:t.wikimedia_commons?.startsWith('Category:')?t.wikimedia_commons.replace(/^Category:/,''):null,_commons:t.wikimedia_commons?.startsWith('File:')?t.wikimedia_commons.replace(/^File:/,''):null,openingHours:clean(t.opening_hours)||null,phone:phone(t['contact:phone']||t.phone),email:mail(t['contact:email']||t.email),address:addressFromTags(t),bookingUrl:url(t.booking||t.reservation||t['contact:booking']),fee:clean(t.fee)||null,wheelchair:clean(t.wheelchair)||null,operator:clean(t.operator)||null,detailSources:osmDetailSources(t,sourceUrl),status:'active',lastChecked:TODAY,lastDetailsChecked:TODAY,lastOsmDetailsChecked:TODAY,_score:score(t,k),image:null});}counts[k]=(counts[k]||0)+1}
console.log(`Usable candidates: ${candidates.length}; ${JSON.stringify(counts)}.`);
const current=JSON.parse(await fs.readFile(FILE,'utf8'));
const curated=current.filter(p=>p.sourceType!=='openstreetmap').map(p=>({...p,sourceType:p.sourceType||'curated',image:p.image||{...fallback(p.categories||[]),alt:`${p.name} category image`}}));
const previousOsm=new Map(current.filter(p=>p.sourceType==='openstreetmap'&&p.sourceId).map(p=>[p.sourceId,p]));
const usedNames=new Set(curated.map(p=>norm(p.name))),usedSlugs=new Set(curated.map(p=>p.slug)),accepted=[];
for(const p of candidates){const n=norm(p.name);if(!n||usedNames.has(n)||usedSlugs.has(p.slug))continue;if(curated.some(c=>km(p.latitude,p.longitude,c.latitude,c.longitude)<.08))continue;const old=previousOsm.get(p.sourceId);if(old?.image&&!old.image.isFallback)p.image={...old.image,alt:old.image.alt||`${p.name}, Tasmania`};usedNames.add(n);usedSlugs.add(p.slug);accepted.push(p)}
const selected=balanced(accepted,TARGET);
if(selected.length<300)console.warn(`Discovery returned only ${selected.length} usable new places; continuing so the prior-catalogue recovery step can restore missing records from the healthy snapshot.`);
const wd=await wikidata(selected.filter(p=>!p.image).map(p=>p.wikidata));for(const p of selected)if(!p.image&&!p._commons&&p.wikidata&&wd.has(p.wikidata))p._commons=wd.get(p.wikidata);
const cm=await commons(selected.filter(p=>!p.image).map(p=>p._commons));
let preservedImages=0;
for(const p of selected){if(p.image&&!p.image.isFallback)preservedImages++;else p.image=p._commons&&cm.has(p._commons)?{...cm.get(p._commons),alt:`${p.name}, Tasmania`}:{...fallback(p.categories),alt:`${p.name} category image`};delete p._commons;delete p._score}
const merged=[...curated,...selected].sort((a,b)=>a.region.localeCompare(b.region)||a.town.localeCompare(b.town)||a.name.localeCompare(b.name));
await fs.writeFile(FILE,`${JSON.stringify(merged,null,2)}\n`);
console.log(`Catalogue: ${curated.length} curated + ${selected.length} OSM = ${merged.length} places; preserved ${preservedImages} licensed OSM image(s) from the previous catalogue.`);